<header class="flex flex-wrap sm:justify-start sm:flex-nowrap z-50 w-full mb-8 bg-orange-700 text-sm py-3 sm:py-0">
    <nav class="relative max-w-[85rem] w-full mx-auto px-4 sm:flex sm:items-center sm:justify-between sm:px-6 lg:px-8">
        <div class="flex items-center justify-between">
            <a class="flex-none text-xl font-semibold text-white" href="/" title="Crud Básico Caju"
                aria-label="Crud Básico Caju">Crud Básico Caju</a>
        </div>

        <!-- Puro enfeite, mas acho usar tailwind interessante pois facilita muito o trabalho de criação de um layout dessa -->

        <div id="navbar-collapse-with-animation"
            class="hidden overflow-hidden transition-all duration-300 basis-full grow sm:block">
            <div
                class="flex flex-col gap-y-4 gap-x-0 mt-5 sm:flex-row sm:items-center sm:justify-end sm:gap-y-0 sm:gap-x-7 sm:mt-0 sm:ps-7">
                <a class="font-medium text-white sm:py-6" href="#" aria-current="page">Landing</a>
                <a class="font-medium text-white/[.8] hover:text-white sm:py-6" href="#">Account</a>
                <a class="font-medium text-white/[.8] hover:text-white sm:py-6" href="#">Work</a>
                <a class="font-medium text-white/[.8] hover:text-white sm:py-6" href="#">Blog</a>

                <a class="flex items-center gap-x-2 font-medium text-white/[.8] hover:text-white sm:border-s sm:border-white/[.3] sm:my-6 sm:ps-6"
                    href="#">
                    <svg class="flex-shrink-0 w-4 h-4" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                        viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                        stroke-linejoin="round">
                        <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
                        <circle cx="12" cy="7" r="4" />
                    </svg>
                    Log in
                </a>
            </div>
        </div>
    </nav>
</header>